"""[fix] created UserPublish for idential models UserStories and UserMoments

Revision ID: 0bf9d50bd7be
Revises: 7254511420c0
Create Date: 2024-02-29 17:34:48.959251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf9d50bd7be'
down_revision: Union[str, None] = '7254511420c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_moments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=False))

    with op.batch_alter_table('user_moments', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
